### ISSUE TITLE
Settings - Modify System Files

### ISSUE THREAD

**Issue by TheMrIron2** [Game-Fusion/SmartPlay3#4]
I would like help with the security of "Modify System Files". It seems like a barebones shell right now.

**Comment by MCFunRide** [comment]
You've got help. I've added on a render function for the desktop settings and stopped any access to the "edit" command in the Settings file. This should decrease the chance of any security holes. Just hang tight and I'll have a working settings page sorted.

**Comment by TheMrIron2** [comment]
Thanks for the settings menu. Original issue was that when files were opened for modification, they were not correctly exited with fs.close().
